
CREATE DATABASE NEWS_PORTAL_NODE;
USE NEWS_PORTAL_NODE;
CREATE TABLE NEWS (
    ID_NEWS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100),
    NEWS TEXT,
    DATA_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DESCRIBE NEWS;

INSERT INTO NEWS (TITLE,NEWS) VALUES ('MY TITULO', 'CONTENIDO DE LAS NOTICIAS');

SELECT * FROM NEWS;